---
- name: 'Sampple for ETCD Module'
  hosts: localhost
  become: false
  tasks:
    ## Basic sample usage for ETCD Module
    - name: 'Set Key-Value on etcd'
      etcd: 
        state: present 
        host: 127.0.0.1
        port: 2379 
        key: /test/ectd_key 
        value: etcd_record
      delegate_to: localhost
      connection: local

    - name: 'Set the same Key-Value on etcd'
      etcd: 
        state: present 
        host: 127.0.0.1
        port: 2379 
        key: /test/ectd_key 
        value: etcd_record
      delegate_to: localhost
      connection: local

    - name: 'Search the Key on ETCD'
      debug: 
        msg: "The ETCD contains '{{ lookup('etcd2', '/test/ectd_key') }}' value"

    - name: 'Delete Key-Value from ETCD'
      etcd:
        state: absent
        host: 127.0.0.1
        port: 2379
        key: /test/ectd_key 
      delegate_to: localhost
      connection: local

