---
- name: 'Sample for ETCD Module'
  hosts: localhost
  become: false
  connection: local
  pre_tasks:
    - name: 'Sample Populate'
      etcd:
        state: present
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        #host: 127.0.0.1
        #port: 4001
        override: true
      with_items:
        - { 'key': 'key_001', 'value': 'value_001' } 
        - { 'key': 'key_002', 'value': 'value_002' } 
        - { 'key': 'key_003', 'value': 'value_003' } 
        - { 'key': 'key_004', 'value': 'value_004' } 
        - { 'key': 'key_folder/fold_key_001', 'value': 'val_fold_001' } 
        - { 'key': 'key_folder/fold_key_002/inner_01', 'value': 'inner_001' } 
        - { 'key': 'key_folder/fold_key_002/inner_02/in_inner_02', 'value': 'in_inner_002' } 
        - { 'key': 'key_folder/fold_key_002/inner_02/in_inner_03', 'value': 'in_inner_003' } 
        - { 'key': 'key_folder/fold_key_002/inner_02/in_inner_04', 'value': 'in_inner_004' } 
        - { 'key': 'key_folder/fold_key_002/inner_02/in_inner_05', 'value': 'in_inner_005' } 
        - { 'key': 'key_folder/key_003/test_01', 'value': 'value_003_test_01' } 
        - { 'key': 'key_folder/key_003/test_02/inner_test_02', 'value': 'lvl4' } 
        - { 'key': 'key_folder/key_004', 'value': 'value_004' } 

    - name: 'Getting variables from ETCD'
      set_fact:
        VAR_MAP: "{{ lookup('etcd','/') }}"

    - name: '[DEBUG] K-V From ETCD'
      debug:
        var: VAR_MAP
        verbosity: 1

  tasks:
    ## Basic sample usage for ETCD Module
    - name: 'Set Key-Value on etcd'
      etcd: 
        state: present 
        key: /test/ectd_key 
        value: etcd_record

    - name: 'Set the same Key-Value on etcd'
      etcd: 
        state: present 
        host: 127.0.0.1
        port: 2379 
        key: /test/ectd_key 
        value: etcd_record

    - name: 'Search the Key on ETCD'
      debug: 
        msg: "The ETCD contains '{{ lookup('etcd', '/test/ectd_key') }}' value"

    - name: 'Delete Key-Value from ETCD'
      etcd:
        state: absent
        host: 127.0.0.1
        port: 2379
        key: /test/ectd_key 

